### ISSUE TITLE
Error on non CUDA machine

### ISSUE THREAD

**Issue by rjalexa** [racai-ai/pyeurovoc#1]
Attempted the sample program as follows:

```
from pyeurovoc import *
model = EuroVocBERT(lang='it')
outputs = model("n una recente sentenza del 25 novembre 2020, di cui la stampa ha dato notizia cinque giorni dopo, la Corte di Cassazione avrebbe accettato la tesi secondo la quale esisterebbe un nesso di causalità tra le vaccinazioni somministrate a Fabio Mondello, un volontario in ferma breve dell'Esercito, e la sua scomparsa dovuta ad una leucemia fulminante;")

```
but get ->
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

The above on my Apple Mac mini 2020 with M1 chip.

Is there any option I can give to avoid this error? Thank you very much.

**Comment by avramandrei** [comment]
Hi,

Thank you for reporting this issue. Most likely your MacBook does not have a GPU with CUDA installed. In this case I recommand you to use the model on a CPU by initializing the model as follows:

`model = EuroVocBERT(lang='it', device="cpu")`

Please let me know if this worked out you.

Bests,
Andrei-Marius Avram

**Comment by rjalexa** [comment]
Sorry I have found the solution myself.
It is sufficient to call like this:
`model = EuroVocBERT(lang='it', device='cpu')`

**Comment by rjalexa** [comment]
:) we wrote the same solution in the same instant :)

**Comment by avramandrei** [comment]
Oh, I see that. I am glad you found the solution. :)

**Comment by rjalexa** [comment]
Thank you VERY much :)
